/*
 * generated by Xtext
 */
package org.xtext.example.xbase.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExampleUiModule extends org.xtext.example.xbase.ui.AbstractExampleUiModule {
	public ExampleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
