/**
 * generated by Xtext
 */
package org.xtext.quickfix.ui.contentassist;

import org.xtext.quickfix.ui.contentassist.AbstractExampleQuickfixProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class ExampleQuickfixProposalProvider extends AbstractExampleQuickfixProposalProvider {
}
