/*
 * generated by Xtext
 */
package org.xtext.quickfix.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.quickfix.ui.internal.ExampleQuickfixActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class ExampleQuickfixExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ExampleQuickfixActivator.getInstance().getBundle();
	}

	@Override
	protected Injector getInjector() {
		return ExampleQuickfixActivator.getInstance().getInjector(ExampleQuickfixActivator.ORG_XTEXT_QUICKFIX_EXAMPLEQUICKFIX);
	}

}
