/*
* generated by Xtext
*/
package org.xtext.quickfix;

/**
 * Initialization support for running Xtext languages
 * without equinox extension registry
 */
public class ExampleQuickfixStandaloneSetup extends ExampleQuickfixStandaloneSetupGenerated{

	public static void doSetup() {
		new ExampleQuickfixStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
