/*
 * generated by Xtext
 */
package org.xtext.quickfix;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExampleQuickfixRuntimeModule extends org.xtext.quickfix.AbstractExampleQuickfixRuntimeModule {

}
