/*
 * generated by Xtext
 */
package org.xtext.example.xbase.ui.contentassist

import org.xtext.example.xbase.ui.contentassist.AbstractExampleProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ExampleProposalProvider extends AbstractExampleProposalProvider {
}
