/*
 * generated by Xtext
 */
package org.xtext.quickfix.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExampleQuickfixUiModule extends org.xtext.quickfix.ui.AbstractExampleQuickfixUiModule {
	public ExampleQuickfixUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
