/*
 * generated by Xtext
 */
package org.xtext.example.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.services.UnorderedgroupsGrammarAccess;

public class UnorderedgroupsParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private UnorderedgroupsGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.parser.antlr.internal.InternalUnorderedgroupsParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.parser.antlr.internal.InternalUnorderedgroupsParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Employee";
	}
	
	public UnorderedgroupsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(UnorderedgroupsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
