/**
 * generated by Xtext
 */
package org.xtext.example.xbase.validation;

import org.xtext.example.xbase.validation.AbstractExampleValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ExampleValidator extends AbstractExampleValidator {
}
