/*
* generated by Xtext
*/
package org.xtext.example;

/**
 * Initialization support for running Xtext languages
 * without equinox extension registry
 */
public class UnorderedgroupsStandaloneSetup extends UnorderedgroupsStandaloneSetupGenerated{

	public static void doSetup() {
		new UnorderedgroupsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
