/*
 * generated by Xtext
 */
package org.xtext.example.ui.contentassist

import org.xtext.example.ui.contentassist.AbstractUnorderedgroupsProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class UnorderedgroupsProposalProvider extends AbstractUnorderedgroupsProposalProvider {


}
