/*
* generated by Xtext
*/
package org.xtext.quickfix.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ExampleQuickfixAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
	return classLoader.getResourceAsStream("org/xtext/quickfix/parser/antlr/internal/InternalExampleQuickfix.tokens");
	}
}
