/*
 * generated by Xtext
 */
package org.xtext.quickfix.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.quickfix.services.ExampleQuickfixGrammarAccess;

public class ExampleQuickfixParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ExampleQuickfixGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.quickfix.parser.antlr.internal.InternalExampleQuickfixParser createParser(XtextTokenStream stream) {
		return new org.xtext.quickfix.parser.antlr.internal.InternalExampleQuickfixParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public ExampleQuickfixGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ExampleQuickfixGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
