/*
 * generated by Xtext
 */
package org.xtext.quickfix.validation

import org.eclipse.xtext.validation.Check
import org.xtext.quickfix.exampleQuickfix.City
import org.xtext.quickfix.exampleQuickfix.ExampleQuickfixPackage

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class ExampleQuickfixValidator extends AbstractExampleQuickfixValidator {

	public static final String INVALID_NAME = "org.xtext.quickfix.InvalidTypeName";

	@Check
	def void checkTypeNameStartsWithCapital(City city) {
		if (city.getName() == null || city.getName().length() == 0) return;
		if (!Character.isUpperCase(city.getName().charAt(0))) {
			warning("Name should start with a capital letter.",
					ExampleQuickfixPackage.Literals.CITY__NAME, INVALID_NAME,
					city.getName());

		}
	}

	public static final String CITY_NOT_INTERESTING = "xtext.workshop.advanced.quickfix.CityNotInteresting";

	@Check
	def void checkAtLeastOneSight(City city) {
		if (city.getSights().size() == 0) {
			warning("City not interesting - no sights specified.", city,
					ExampleQuickfixPackage.Literals.CITY__NAME, CITY_NOT_INTERESTING);
		}
	}

}
