/*
 * generated by Xtext
 */
package org.xtext.example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UnorderedgroupsUiModule extends org.xtext.example.ui.AbstractUnorderedgroupsUiModule {
	public UnorderedgroupsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
