/*
* generated by Xtext
*/
package org.xtext.example.xbase;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ExampleUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.example.xbase.ui.internal.ExampleActivator.getInstance().getInjector("org.xtext.example.xbase.Example");
	}
	
}
