/*
 * generated by Xtext
 */
package org.xtext.example.xbase;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExampleRuntimeModule extends org.xtext.example.xbase.AbstractExampleRuntimeModule {

}
