/*
 * generated by Xtext
 */
package org.xtext.example.xbase.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.xbase.ui.internal.ExampleActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ExampleExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ExampleActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ExampleActivator.getInstance().getInjector(ExampleActivator.ORG_XTEXT_EXAMPLE_XBASE_EXAMPLE);
	}
	
}
